name: Build
on:
  release:
    types: [created]

jobs:
  build:
    name: Build Executable
    runs-on: windows-latest
    steps:
      - name: "[SETUP] Checkout"
        uses: actions/checkout@v2
      - name: "[SETUP] Python 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: "[SETUP] Install Requirements"
        run: python3 -m pip install -r requirements.txt
      - name: "[SETUP] Install PyInstaller"
        run: python3 -m pip install pyinstaller
      - name: "[BUILD] Build Executable"
        run: pyinstaller --onefile MureongFloorCalculator.py
      - name: "[WRAPUP] Change Location on Built Executable"
        run: Move-Item -Path .\\dist\\MureongFloorCalculator.exe -Destination .\\MureongFloorCalculator.exe
      - name: "[WRAPUP] Compress Outputs"
        run: 7z a -tzip MureongCalc.zip MureongFloorCalculator.exe Character.property
      - name: "[UPLOAD] Upload Asset"
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: MureongCalc.zip
